### ISSUE TITLE
How to get into graphic mode after installing

### ISSUE THREAD

**Issue by tatung** [thenewvu/minimal-ubuntu-setup#1]
I have run minimal-ubuntu-setup as instruction. After finishing installing, I tried to reboot into graphic mode but I can only get into command line. How to boot to graphic mode?

Thanks

**Comment by tatung** [comment]
I have tried to run `startx` and have got into the X (pretty same as your screen shot). However, I cannot do anything more. How to start terminal, or chrome for example?

Thanks!

**Comment by tatung** [comment]
Never mind this! I have managed to use it. Just my lacking knowledge of `i3` window manager!
For reference, here is i3 manual:
https://i3wm.org/docs/userguide.html#_default_keybindings

**Comment by thenewvu** [comment]
It's okay. I have been in that situation before just like you. I did not refer to 'how to work with it' just because it should be easy. 

One more thing, the setup was built base on my need. Tweak it to fit your need.

Have fun with it.
Thank you!

**Comment by tatung** [comment]
OK, thank you! You did a great job!
